package:
    type:           library
    name:           omnipay-paxum
    title:          Paxum plugin for PHP merchant library
    license:        MIT
    headline:       'Omnipay: Paxum'
    keywords:       php, omnipay, paxum, merchant, payment
    namespace:      Omnipay\Paxum
    description:    |
        [Omnipay](https://github.com/omnipay/omnipay) is a framework agnostic, multi-gateway payment
        processing library for PHP 5.3+.

        This package implements [Paxum](https://paupal.com/) support for Omnipay.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
